# Generated by Django 3.1.4 on 2020-12-31 23:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionDate', models.DateField(default='', max_length=50)),
                ('TransactionType', models.CharField(default='', max_length=50)),
                ('Amount', models.DecimalField(decimal_places=2, default='', max_digits=50)),
                ('Account', models.CharField(default='', max_length=50)),
            ],
            managers=[
                ('trans', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='', max_length=50)),
                ('LastName', models.CharField(default='', max_length=50)),
                ('StartingBalance', models.DecimalField(decimal_places=2, default='', max_digits=50)),
            ],
        ),
    ]
