# Generated by Django 3.1.4 on 2020-12-30 02:32

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=50)),
                ('CourseNumber', models.IntegerField(default='', max_length=50)),
                ('InstructorName', models.CharField(default='', max_length=50)),
                ('Duration', models.FloatField(default='', max_length=50)),
            ],
            managers=[
                ('course', django.db.models.manager.Manager()),
            ],
        ),
    ]
